import { describe, expect, it } from "vitest";

import { contentTypeOf, decodeBody, encodeBody } from "./body.js";

describe("encodeBody", () => {
  it("produces no body for undefined or null", () => {
    // A bodyless POST must not send the four characters "null".
    expect(encodeBody(undefined)).toEqual({ body: undefined, contentType: undefined });
    expect(encodeBody(null)).toEqual({ body: undefined, contentType: undefined });
  });

  it("JSON-encodes a plain object and declares the type", () => {
    const encoded = encodeBody({ a: 1 });
    expect(encoded.body).toBe('{"a":1}');
    expect(encoded.contentType).toBe("application/json");
  });

  it("JSON-encodes arrays, numbers, and booleans", () => {
    expect(encodeBody([1, 2]).body).toBe("[1,2]");
    expect(encodeBody(42).body).toBe("42");
    expect(encodeBody(true).body).toBe("true");
  });

  it("passes FormData through without setting a content type", () => {
    // The boundary parameter is generated by the runtime at send time. Setting
    // the header by hand produces one that does not match the payload, which is
    // why every client this replaces special-cased FormData.
    const form = new FormData();
    form.set("a", "b");
    const encoded = encodeBody(form);
    expect(encoded.body).toBe(form);
    expect(encoded.contentType).toBeUndefined();
  });

  it.each([
    ["string", "already encoded"],
    ["URLSearchParams", new URLSearchParams({ a: "b" })],
    ["Blob", new Blob(["x"])],
    ["ArrayBuffer", new ArrayBuffer(4)],
    ["typed array", new Uint8Array([1, 2, 3])],
  ])("passes %s through untouched", (_label, value) => {
    const encoded = encodeBody(value);
    expect(encoded.body).toBe(value);
    expect(encoded.contentType).toBeUndefined();
  });
});

function res(body: BodyInit | null, init: ResponseInit = {}) {
  return new Response(body, init);
}

/**
 * A response carrying no `Content-Type` at all.
 *
 * `new Response("...")` sets `text/plain;charset=UTF-8` on the caller's behalf,
 * so a string body cannot express "the server declared nothing". A Blob with an
 * empty type can.
 */
function untypedRes(body: string) {
  return new Response(new Blob([body], { type: "" }));
}

describe("decodeBody", () => {
  it("parses JSON that carries a charset parameter", async () => {
    // The regression this exists for: an exact-equality comparison against
    // "application/json" sent every real-world response down the binary path.
    const r = res('{"a":1}', { headers: { "Content-Type": "application/json; charset=utf-8" } });
    await expect(decodeBody(r, "auto", "GET")).resolves.toEqual({ a: 1 });
  });

  it("parses a +json structured suffix type", async () => {
    const r = res('{"a":1}', { headers: { "Content-Type": "application/vnd.api+json" } });
    await expect(decodeBody(r, "auto", "GET")).resolves.toEqual({ a: 1 });
  });

  it("matches the content type case-insensitively", async () => {
    const r = res('{"a":1}', { headers: { "Content-Type": "Application/JSON" } });
    await expect(decodeBody(r, "auto", "GET")).resolves.toEqual({ a: 1 });
  });

  it.each([204, 205, 304])("returns undefined for a bodyless %d", async (status) => {
    // Calling .json() here is what threw in the original clients.
    const r = res(null, { status });
    await expect(decodeBody(r, "auto", "GET")).resolves.toBeUndefined();
  });

  it("returns undefined for a HEAD response whatever the status", async () => {
    const r = res(null, { status: 200, headers: { "Content-Type": "application/json" } });
    await expect(decodeBody(r, "auto", "HEAD")).resolves.toBeUndefined();
  });

  it("returns undefined for an empty JSON body rather than throwing", async () => {
    const r = res("", { headers: { "Content-Type": "application/json" } });
    await expect(decodeBody(r, "auto", "POST")).resolves.toBeUndefined();
  });

  it("decodes a textual type to a string", async () => {
    const r = res("hello", { headers: { "Content-Type": "text/plain" } });
    await expect(decodeBody(r, "auto", "GET")).resolves.toBe("hello");
  });

  it("falls back to a Blob for a binary type", async () => {
    const r = res("bytes", { headers: { "Content-Type": "application/octet-stream" } });
    const decoded = await decodeBody<Blob>(r, "auto", "GET");
    expect(decoded).toBeInstanceOf(Blob);
  });

  it("guesses JSON when no content type is declared", async () => {
    await expect(decodeBody(untypedRes('{"a":1}'), "auto", "GET")).resolves.toEqual({ a: 1 });
  });

  it("falls back to text when an undeclared body is not JSON", async () => {
    // An untyped body is not itself an error, so this must not throw.
    await expect(decodeBody(untypedRes("not json at all"), "auto", "GET")).resolves.toBe(
      "not json at all",
    );
  });

  it("returns undefined for an undeclared empty body", async () => {
    await expect(decodeBody(untypedRes(""), "auto", "GET")).resolves.toBeUndefined();
  });

  it("propagates a parse error when the server declared JSON and lied", async () => {
    const r = res("{oh no", { headers: { "Content-Type": "application/json" } });
    await expect(decodeBody(r, "auto", "GET")).rejects.toThrow();
  });

  describe("explicit modes", () => {
    it("none reads nothing", async () => {
      const r = res('{"a":1}', { headers: { "Content-Type": "application/json" } });
      await expect(decodeBody(r, "none", "GET")).resolves.toBeUndefined();
      expect(r.bodyUsed).toBe(false);
    });

    it("text overrides a JSON content type", async () => {
      const r = res('{"a":1}', { headers: { "Content-Type": "application/json" } });
      await expect(decodeBody(r, "text", "GET")).resolves.toBe('{"a":1}');
    });

    it("json overrides a text content type", async () => {
      const r = res('{"a":1}', { headers: { "Content-Type": "text/plain" } });
      await expect(decodeBody(r, "json", "GET")).resolves.toEqual({ a: 1 });
    });

    it("stream hands back the body without reading it", async () => {
      const r = res("data", { headers: { "Content-Type": "text/plain" } });
      const stream = await decodeBody<ReadableStream>(r, "stream", "GET");
      expect(stream).toBeInstanceOf(ReadableStream);
      expect(r.bodyUsed).toBe(false);
    });

    it("arrayBuffer and blob decode binary", async () => {
      const a = res("xy");
      expect(await decodeBody<ArrayBuffer>(a, "arrayBuffer", "GET")).toBeInstanceOf(ArrayBuffer);
      const b = res("xy");
      expect(await decodeBody<Blob>(b, "blob", "GET")).toBeInstanceOf(Blob);
    });
  });
});

describe("contentTypeOf", () => {
  it("strips parameters and lower-cases", () => {
    const r = res("{}", { headers: { "Content-Type": "Application/JSON; charset=UTF-8" } });
    expect(contentTypeOf(r)).toBe("application/json");
  });

  it("returns an empty string when the header is absent", () => {
    expect(contentTypeOf(res(null, { status: 204 }))).toBe("");
  });
});
